name: WordPress Podman Check

on:
  push:
    branches:
      - main

jobs:
  container-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Podman
        run: podman --version

      - name: Build backend image
        run: podman build -t sks-backend ./backend

      - name: Build WordPress image
        run: podman build -t sks-wp-app ./wordpress

      - name: Build frontend image
        run: podman build -t sks-frontend ./frontend

      - name: List images
        run: podman images
